<Project>
    <!-- Versions par défaut -->
    <PropertyGroup>
        <DefaultTargetFramework>net10.0</DefaultTargetFramework>
        <AspNetNugetVersion>10.*</AspNetNugetVersion>
        <NpgsqlNugetVersion>10.*</NpgsqlNugetVersion>
        <OpenTelemetryNugetVersion>1.15.*</OpenTelemetryNugetVersion>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <StyleCopTreatErrorsAsWarnings>false</StyleCopTreatErrorsAsWarnings>
        <UserSecretsId>178d6264-543f-4175-af83-94b88ff07ec7</UserSecretsId>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)\stylecop.json" />
    </ItemGroup>
</Project>